### ISSUE TITLE
When adding new Analysis Request from clinic then upload an attachment the systems doesn't generate the requisition form report 

### ISSUE THREAD

**Issue by tdiphale** [bhp-lims/bhp.lims#106]
## Steps to reproduce

1. Add a new Analysis Request 
2. Fill all the required information
3. Attach a file
4. Submit the requisition 
5. Open the recently added requisition
6. Click under attachments
 
## Current behavior

When the user uploads an attachment the system does not generate the requisition form report but only shows the file which was uploaded.

## Expected behavior
The system to generate requisition report when user has uploaded attachments 

## Screenshot (optional)
![screen shot 2018-09-07 at 11 39 32](https://user-images.githubusercontent.com/41940041/45213302-75be1f00-b297-11e8-9a77-6f6e0e414532.png)

**Comment by xispa** [comment]
Fixed in https://github.com/senaite/senaite.core/pull/1318
