### ISSUE TITLE
Template for invalidation email

### ISSUE THREAD

**Issue by ramonski** [bhp-lims/bhp.lims#113]
## Description

Currently it is only possible to allow/disallow email notification on invalidation.
It would be nice to specify an email template there as well

**Comment by xispa** [comment]
Duplicate of https://github.com/bhp-lims/bhp.lims/issues/130 and https://github.com/bhp-lims/bhp.lims/issues/116
Fixed in https://github.com/senaite/senaite.core/pull/1244
