### ISSUE TITLE
Modify text associated with invalid results when sending an email to client in email template

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#116]
## Current behavior
so far when you send the client email concerning the invalid results, it displays the default message
## Expected behavior
We must add some additional information when sending the client the message concerning invalid results

**Comment by xispa** [comment]
Duplicate of https://github.com/bhp-lims/bhp.lims/issues/130
Fixed in https://github.com/senaite/senaite.core/pull/1244
