### ISSUE TITLE
The system  should  allow cases to track who reviewed/verified and published the result.

### ISSUE THREAD

**Issue by tdiphale** [bhp-lims/bhp.lims#156]
## Steps to reproduce
1. Create an AR
2. Send AR To Lab
3. Process,Verify and publish Results

## Current behavior
Currently on the result reports, the system allows ‘reviewed by’ and ‘published by’ to be the same person. 

## Expected behavior
The system should therefore allow such cases by being able to track who reviewed/verified and published the result.

**Comment by xispa** [comment]
Duplicate of https://github.com/bhp-lims/bhp.lims/issues/188
