### ISSUE TITLE
The system should allow clients to print requisition forms from AR page

### ISSUE THREAD

**Issue by tdiphale** [bhp-lims/bhp.lims#159]
The system should allow clients to print requisition forms from AR page in addition to accessing the forms by clicking on the request IDs…The same functionality of ‘print stickers’ on the AR page should also be available to—not a show stopper

      ‘print requisition forms’.

**Comment by xispa** [comment]
New button has been added at the bottom of the list. The user can select multiple ARs at once and when the button is pressed. Once clicked, a pdf is generated with all the requisition PDFs from all selected ARs

![captura de 2019-02-17 22-13-15](https://user-images.githubusercontent.com/832627/52919322-95a34580-3301-11e9-97a3-52a6b813f432.png)
