### ISSUE TITLE
After publishing the results pdf's are not there under published results tab

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#164]
## Steps to reproduce
create an Analysis Request
send an AR to lab
process an AR at lab
verify the results for AR
publish the results

## Current behavior
After publishing the results PDF's are not there under published results tab

## Expected behavior
Results PDF's are supposed to be appearing in the published results tab

## Screenshot (optional)
![lis](https://user-images.githubusercontent.com/12894381/46784290-c957d880-cd2d-11e8-8a56-c367301941e0.jpeg)

**Comment by xispa** [comment]
I am pretty sure this works in the pilot instance. Please, double-check
