### ISSUE TITLE
= has not yet been added to quantifiers for RNA PCR

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#165]
## Steps to reproduce
1. Create an analysis request
2. Send sample to lab
3. Receive at reception
4. Send to POT
5. Receive at POT
6. Introduce results (for the viral load quantifier code the is no '=' sign there is only '<' and '>')
## Current behavior
 -= has not yet been added to quantifiers for RNA PCR 

## Expected behavior
1. Create an analysis request
2. Send sample to lab
3. Receive at reception
4. Send to POT
5. Receive at POT
6. Introduce results (for the viral load quantifier code the is no '=' sign there is only '<' and '>' there should be '=' also
![missing equal sign](https://user-images.githubusercontent.com/4726008/46815120-8839e580-cd7a-11e8-9edc-9bce7bdc4a5a.jpeg)
)

**Comment by xispa** [comment]
There is no need to add a quantifier. Select the empty option from the selection list.
See https://github.com/senaite/senaite.core/pull/1039

**Comment by xispa** [comment]
That selection list is to allow the analyst to set the Detection Limit manually: if the analyst selects the option "<" and introduces the value "0.05", it means that the result is below 0.05, but the "exact" value is not known. It has no sense to add the option "=" there. If you want to introduce a result that is within the limits, you only need to introduce the result and leave the DL selector empty (neither "<" nor ">" selected).

If you don't want the user to be able to choose a detection limit there, then disable the option "Display a Detection Limit selector" for "RNA PCR" in Analysis Service (in Setup > Analysis Services > HIV Viral Load (RNA PCR). Then, that selector will not appear anymore, but if the analyst introduces a result below the LDL, the system will not display the "exact" value anymore anywhere, only "< [LDL]"
