### ISSUE TITLE
Panic level function details is not clarified in the system

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#166]
## Current behavior
we do not know how the panic levels works at the moment

## Expected behavior
To know exactly how panic level works in the system

**Comment by xispa** [comment]
Please read https://github.com/bhp-lims/bhp.lims/pull/162

**Comment by xispa** [comment]
Closing this one. Atm, there is the possibility to define the min and max panic level threshold in results_ranges.xlsx. As per previous conversations with Dr.Moyo, there is the need of adding 4 different grades in results_ranges.xlsx, so panic levels will be sent in accordance to those results that are above/below the 2th grade. Grade will be displayed in results report too.
