### ISSUE TITLE
Allow dropdown menu for volume units when creating an analysis request

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#167]
## Steps to reproduce
Create an analysis request
Enter volume units in the volume field
 
## Current behavior
volume units are entered manually when creating an analysis request

## Expected behavior
volume field must have dropdown to allow someone requesting an ar to select the units or if they dont need units to select N/A

**Comment by xispa** [comment]
Please, provide the selection list options to be displayed in this Unit selection list. 
Also, this issue to be considered as an addition to [ Volume field with separate input boxes for volume, units and not applicable #12](https://github.com/bhp-lims/bhp.lims/issues/12)

**Comment by cmaphorisa** [comment]
The list should include: micro litres (uL), mili litres (mL), litres (L) and "other"
