### ISSUE TITLE
Emails do not have an attachment results form after publishing results

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#178]
## Steps to reproduce

Order an AR
send to Lab
Receive at reception
Send to point of testing 
Receive at point of testing
Process an AR
Verify an AR
Publish the results

## Current behavior
Emails do not have an attachment results form after publishing results

## Expected behavior
Emails should have an attachment results form after publishing results

**Comment by xispa** [comment]
@MoffatMore I've checked agains the pilot instance (an exact copy of production instance) and the emails are sent correctly, with results report attached. The following is the AR I've created and pre-published: https://senaite-server.bhp.org.bw/clients/client-14/02AAA0101

I've received an email with the results report attached in pdf format as expected:
![captura de pantalla de 2019-01-22 09-40-21](https://user-images.githubusercontent.com/832627/51522638-22093800-1e2a-11e9-8828-531669a1a0b4.png)

If you are referring to attachments other than the results report itself (e.g. requisition report, etc.), then remember the system is configured in a way that users must select them in the email preview on publish:

![captura de pantalla de 2019-01-22 09-18-44](https://user-images.githubusercontent.com/832627/51522756-64327980-1e2a-11e9-97e9-cdc3ac817c48.png)

Please, confirm!

**Comment by MoffatMore** [comment]
@xispa

**Comment by MoffatMore** [comment]
we went through the system (production instance) with Comfort earlier and reproduced the error again,
basically when you login as a clinician specifically for IMPACT 2010 study, and order an analysis request, after the results are being published at the lab, the email will be sent to the clinic 
(IMPACT 2010) without results report attachment, and we have noticed that this happens only with this particular study, other studies are OK when receiving email with attachment
Below is the screenshot of the email that is been received by the clinic about the results
<img width="504" alt="screen shot 2019-01-22 at 14 14 42" src="https://user-images.githubusercontent.com/12894381/51536098-1e3ddb80-1e53-11e9-91bc-f9b25f5df347.png">

**Comment by xispa** [comment]
Was fixed in https://github.com/bhp-lims/bhp.lims/issues/188
