### ISSUE TITLE
 Percentage of progress does not show when doing reception and sending to point of testing

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#181]
## Steps to reproduce
create an analysis request
send to lab
receive at reception
send to point of testing
receive at point of testing

## Current behavior
 Percentage of progress does not show when sending to reception and sending to point of testing

## Expected behavior
 Percentage of progress should show when send to reception and sending to point of testing

**Comment by xispa** [comment]
At the moment, percentage of progress represents the progress done regarding analyses itself. This is, before the specimen is at point of testing, no results have been set yet to the analyses the AR contains. Hence, the percentage is 0%. The percentage will start to increase as soon as analysts introduce results and will reach 100% once AR is published.

**Comment by xispa** [comment]
Ok, noted. Please set the priority to this enhancement, thanks.
