### ISSUE TITLE
Result report has no Assay date. Date tested

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#182]
## Steps to reproduce
https://github.com/bhp-lims/bhp.lims/issues/178

## Current behavior
Result report has no Assay date. Date tested. This is a requirement for the ISO standard. Gender should be caps. Change patient ID to participant ID.

## Expected behavior
Result report should have Assay date. Date tested. This is a requirement for the ISO standard. Gender should be caps. Change patient ID to participant ID.

**Comment by xispa** [comment]
@MoffatMore please create one issue per requirement. "Gender should be caps" and "Change patient ID to participant ID" should be two separate issues.

Regarding to the "Assay date", the system allows to set results for analyses at different dates. This is, if you have an Analysis Request with two analyses (say Hb and PT), the capture date from both may differ (e.g. the analyst set a result for Hemoglobyn early in the morning and set a result for Platelets the day after). 

It would work if we assume the "Assay date" is the latest date a result was captured?

Also note the Assay date is different from the verification date.

**Comment by MoffatMore** [comment]
Ok, thanks for the reminder i will separate issue per requirement, noted!

about Assay date i will further discuss with Comfort and Terrence to see whether they agree to put it as the latest date results captured

**Comment by xispa** [comment]
Cool thanks. Let me know asap so we can deploy this fix in pilot instance today, together with https://github.com/bhp-lims/bhp.lims/issues/183

**Comment by MoffatMore** [comment]
I meet with Coulson and discuss about this, so he suggested that you make a field for assay date so that the analyst is the one to decide which date to put

**Comment by xispa** [comment]
Ummmm, don't think this is going to be ISO compliant, because user could set an assay date totally different from when the results were actually captured. I still think the best option would be to use the latest capture date.

**Comment by MoffatMore** [comment]
Hie @xispa , i further discussed with Comfort about this assay date, so he also suggested that it will be convenient to have that field even if it is going to be ISO compliant,

**Comment by xispa** [comment]
Ok, thanks!. Will do that then

**Comment by MoffatMore** [comment]
Hie @xispa we went through the changes you have done so far with Comfort, 
so Comfort was suggesting that the field for assay date should be one of the column of table where the analyses results are keyed so that the analyst can also have an option to click on assay date
<img width="1244" alt="screen shot 2019-01-31 at 11 37 55" src="https://user-images.githubusercontent.com/12894381/52045667-adcb4480-254d-11e9-9479-e49a8ee532b8.png">
