### ISSUE TITLE
Delivery checklist should have date received

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#183]
## Steps to reproduce
order an analysis request
send to lab (shipping)
download delivery checklist

## Current behavior
date received is not appearing on the checklist

## Expected behavior
checklist should have date received

**Comment by xispa** [comment]
Delivery report already comes with a field called "Time specimen received at lab":

![captura de pantalla de 2019-01-23 09-55-20](https://user-images.githubusercontent.com/832627/51594916-cf954d80-1ef5-11e9-8955-e6e677ca5943.png)

This report is automatically created by the system when clinicians send the specimen to the lab, so we cannot add a "Date received" field there: when the pdf is created, the specimen hasn't been yet received!.

May I close this issue?

**Comment by xispa** [comment]
Ok, next time please be more specific when creating issues. We spend valuable time otherwise. :P

**Comment by MoffatMore** [comment]
Ok yeah, i think they don't elaborate their issue first until i ask ask for the details, but next time i will make sure i have more information concerning issue when i post it here
