### ISSUE TITLE
Analysis Request table should include visit number

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#190]
## Steps to reproduce

login bhplims
select **analysis request** on the left side navbar
go to analysis request tables

## Current behavior
Currently analysis request table doesn't have column for visit code

## Expected behavior
visit code should be included in analysis request column

## Screenshot (optional)

<img width="874" alt="screen shot 2019-02-12 at 09 09 40" src="https://user-images.githubusercontent.com/12894381/52617882-ee0fb880-2ea5-11e9-9088-a0efeb2b06d9.png">

**Comment by xispa** [comment]
Please confirm if for "Visit code" you are referring to "Visit number" or to "Study code".

**Comment by xispa** [comment]
Fixed in https://github.com/bhp-lims/bhp.lims/pull/196/commits/9c4c65b3e6ed5b1d76f112c6ab31ab30028924c6 (https://github.com/bhp-lims/bhp.lims/pull/196)
