### ISSUE TITLE
Filter analysis request by test requested

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#191]
## Steps to reproduce
login to bhp-lims
go to analysis requests

## Current behavior
unable to filter analysis request by test requested

## Expected behavior
we need to filter analysis request by test requested

## Screenshot (optional)
<img width="874" alt="screen shot 2019-02-12 at 09 09 40" src="https://user-images.githubusercontent.com/12894381/52618127-9b82cc00-2ea6-11e9-891b-c3187bff4801.png">

**Comment by xispa** [comment]
In v1.3 (pilot instance), you can filter for whatever term you like by using the searchbox, on top-right:

![captura de 2019-02-12 10-59-51](https://user-images.githubusercontent.com/832627/52627374-78abe400-2eb5-11e9-9361-97e894d13d8a.png)
