### ISSUE TITLE
Results storage should allow multiple samples to be selected

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#192]
## Current behavior
resulting storage form is not user friendly, not allowing to select multiple samples

## Expected behavior
we need it to allow selecting multiple samples, once "stored" is selected it should complete the step (100%) and no need to verify

**Comment by xispa** [comment]
We haven't deployed the sample storage module in production yet, so not sure what you mean by resulting storage form. 

Storage module will allow you to select multiple samples and store all them at once. It will also allow you to choose a storage container (e.g. through barcode scanning) and add multiple samples to that container by scanning their barcodes, etc.. and plenty of other functionalities.

In storage module, once a sample is "stored", its workflow is decoupled from the rest: "analytical" worfklow ("to be verified", "verified", "published", etc.) don't apply to "stored" samples. You'll need to "recover" them first.

**Comment by cmaphorisa** [comment]
We can close this
