### ISSUE TITLE
Allow editing of analysis request once created

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#193]
## Steps to reproduce
create an ar

## Current behavior
currently it is not possible to do edits without entirely deleting the record

## Expected behavior
should be able to edit an ar once created and regenerate new requisition pdf

**Comment by xispa** [comment]
The edition of fields depends on the Sample status. For example, when Sample is published, system does not allow you to modify i.e. "Sample Type", while the system allows you to modify this field when the Sample is in "ordered" status.

Also, keep in mind that not all users have same per-status permissions on this regard. For instance, Labman can modify Sample Type on reception, but clinic contact cannot.

Besides all this, there are some fields that are strongly bound to the request and cannot be changed once the Sample is created: "Client", for instance. So, when edition for these kind of fields is required, there is no choice other than cancel/invalidate the Sample.

So, what are the fields you want to be editable, by whom and in which status?

**Comment by cmaphorisa** [comment]
The common fields that editing are  participant ID, visit, date sampled, participant initials, date of birth, and sample volume. This is the feed back from the clinic. They desperately need this feature

**Comment by xispa** [comment]
Thanks for the feedback @cmaphorisa . Ticket labeled as `P0: Critical`

**Comment by xispa** [comment]
@cmaphorisa , please check the fields are editable when logged in as client contact. Just checked with `jjarvis` and worked as expected. Please confirm and if it works for you, eventually close the issue. Thanks

**Comment by cmaphorisa** [comment]
@xispa I have checked at the initial stages of the requisition and its working nicely. I will do more intensive tests and give feed back. Well done
