### ISSUE TITLE
Audit trail needed

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#194]
## Current behavior
the system doesn't not keep record of changes that has been made for every entry
 
## Expected behavior
Audit trail needed for every entry, correction or update

**Comment by xispa** [comment]
For every electronic record (e.g. say Sample), the system keeps track of the transitions done, along with the user responsible of that action and the timestamp. You can access to the log from a given electronic record by adding `/log` at the end of the url or by clicking to "Log" tab at top-right. This log is only accessible to Lab Manager and Manager profiles. Field-specific edits are not logged, though.

**Comment by xispa** [comment]
To be available soon https://github.com/senaite/senaite.core/pull/1324

**Comment by xispa** [comment]
Hi @cmaphorisa , we've updated the pilot instance with an early version of the Audit Log function (see my comment above). Please, test it thoroughly (the best would be to simulate multiple use-cases and check if all modifs are kept in the audit log correctly without inconsistencies) and provide feedback!.
