### ISSUE TITLE
Visit code should be included on delivery checklist

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#195]
## Steps to reproduce
create an ar
send to lab
select courier
download courier checklist

## Current behavior
delivery checklist doesn't have column for visit code
## Expected behavior
Delivery checklist should include both visit number and code

**Comment by xispa** [comment]
Related with https://github.com/bhp-lims/bhp.lims/issues/190
Could you clarify what you mean by visit code?

**Comment by cmaphorisa** [comment]
This issue is looking for a drop down menu with visit options such as SCREENING, WEEK 1, WEEK 2 ...., MONTH 1, MONTH 2 ...., DELIVERY, PRE INFUSION, INFUSION, POST INFUSION.

**Comment by cmaphorisa** [comment]
I suggest the field for week, day, month to be called "VISIT" and the one for visit number to be called "VISIT CODE" so that it is consistent with the clinic nomenclature.
