### ISSUE TITLE
Allow the labman to manually set the Assay Date

### ISSUE THREAD

**Issue by xispa** [bhp-lims/bhp.lims#197]
## Steps to reproduce

1. Create a Sample and receive at point of testing
2. Submit results

## Current behavior

The system automatically sets the Assay Date to the Sample as the date time the last result was submitted:

https://github.com/bhp-lims/bhp.lims/blob/e10445dd38780eea46de2ce075867c51cc5547ed/bhp/lims/workflow/analysis/events.py#L10-L16

This Assay Date is later printed in results report.

## Expected behavior

The behavior above is correct, but labman should be able to manually set the Assay Date in Sample's edit view. A new "Assay date" field in Sample's view must be displayed in edit mode for labman when the Sample is in "To be verified" status. A field validator must be added too, so:

- The Assay Date cannot be before the sample was received at point of testing
- The Assay Date cannot be future

**Comment by cmaphorisa** [comment]
I see that the field for assay date has been added but no text can be added
<img width="1205" alt="Screenshot 2019-03-13 at 08 57 19" src="https://user-images.githubusercontent.com/41732301/54260266-1ce68080-4571-11e9-8743-66f329e3b9f2.png">

**Comment by xispa** [comment]
@cmaphorisa the Assay Date is only editable when the specimen is in `to be verified` state as suggested above, in ticket description. Do you want/need the Assay Date to be editable in `verified` state too?

**Comment by cmaphorisa** [comment]
We want the assay date to be added at the same time as the results. It is a parameter that we want the person who is verifying to also review before verifying

**Comment by xispa** [comment]
This https://github.com/bhp-lims/bhp.lims/commit/e0b12b5723dac2dd4c2d25e739975e1800124431 should fix the issue. Assay Date is now editable in `received at point of testing` and `to_be_verified` statuses, for both LabManager and Analyst. @cmaphorisa I've deployed this change to pilot already, please confirm if is now working as expected.

**Comment by cmaphorisa** [comment]
Tested and working
