### ISSUE TITLE
Label the analyses processed by other labs in results report

### ISSUE THREAD

**Issue by xispa** [bhp-lims/bhp.lims#199]
## Steps to reproduce

Some tests are occasionally sent to other labs (referral labs) for their analysis. When the laboratory receives the results from the referral lab, it introduces the results manually into the system. 

## Current behavior

In results report, there is no way to distinguish those analyses that have been tested in the same lab from those that have been tested in referral labs.

## Expected behavior

In results report, a superscript (with a number) is displayed next to the analyses tested in referral labs. At the page footer, the same number with a text (**to be defined**) is displayed accordingly.

Although one might first think about an option like "Analysis tested by another lab", this would not be a solution because is not always the case. Rather, add a column (like "Hidden") in Analyses view with a selection box to allow the labman to "label" the analyses that have been processed by other labs.

**Comment by xispa** [comment]
@cmaphorisa , please post here the text to be displayed in report's footer (legend) for the analyses that have been processed by other labs.

**Comment by cmaphorisa** [comment]
In a report, sometimes we have several tests. Among them some are tested by us while some are tested by the referral lab. e.g. in a chemistry requisition we can have ALT, ALP,creatinine tested here but phosphorus and calcium tested at BARC. We like this to be reflected

**Comment by cmaphorisa** [comment]
The template should be as follows: 'THE FOLLOWING ANALYTES ........... WERE TESTED ........... LAB'.

**Comment by xispa** [comment]
@cmaphorisa please test. Note you need to first create some Referral Laboratories (top-right "gear" icon > Referral Laboratories). Some screenshots here: https://github.com/bhp-lims/bhp.lims/pull/243

**Comment by cmaphorisa** [comment]
I have tested and its working as expected
