### ISSUE TITLE
Retracted results are listed in results report

### ISSUE THREAD

**Issue by xispa** [bhp-lims/bhp.lims#200]
## Steps to reproduce

1. Create a Sample, submit results for analyses
2. Retract one of the analyses
3. Submit the retest
4. Verify and Publish the Sample

## Current behavior

The retracted analysis is displayed in results report. 

## Expected behavior

Retracted analyses should not be displayed in results report.

## Screenshot (optional)

![captura de 2019-02-21 18-34-06](https://user-images.githubusercontent.com/832627/53189241-5463ac00-3607-11e9-97e9-a0c63692e25e.png)

**Comment by xispa** [comment]
Related: https://github.com/senaite/senaite.core/issues/1265

**Comment by cmaphorisa** [comment]
I tested and its working fine
