### ISSUE TITLE
Viral load quantifier DROP DOWN menu doesnt have an = sign

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#201]
## Steps to reproduce
https://github.com/bhp-lims/bhp.lims/issues/165

**Comment by xispa** [comment]
??
Issue without information at all. Are you probably referring to https://github.com/bhp-lims/bhp.lims/issues/165 ?

**Comment by cmaphorisa** [comment]
The quantifier drop down menu only has < and > signs. We need an = sign added.

**Comment by MoffatMore** [comment]
yes i was referring to this https://github.com/bhp-lims/bhp.lims/issues/165

**Comment by cmaphorisa** [comment]
@xispa the "(empty)" option is not available either. That's why we raised the issue

**Comment by xispa** [comment]
Fixed in https://github.com/senaite/senaite.core/pull/1251

**Comment by cmaphorisa** [comment]
I tested and its working fine
