### ISSUE TITLE
Add the option to 'discard' primary requisitions after it's partitions have been stored

### ISSUE THREAD

**Issue by cmaphorisa** [bhp-lims/bhp.lims#214]
## Steps to reproduce
- Create a requisition, send to lab, receive, create partitions, and store partitions
## Current behavior
- The primary requisition remain in the received state
## Expected behavior
- There should be an option to transition the primary sample to 'DISCARDED'

**Comment by xispa** [comment]
The system is configured in such a way the Primary sample status follows the status of its partitions. For instance, if you create two partitions and then you submit results so both of them are transitioned to "to be verified" state, the Primary will follow and will also be transitioned to same status. Same same if you verify all partitions: the primary status will become "verified" too.
