### ISSUE TITLE
After creating more than one ar, not all analysis request's appears in the next page for barcode printing

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#221]
## Steps to reproduce
Create an AR
print barcode stickers

## Current behavior
After creating more than one ar, not all analysis request's appears in the next page for barcode printing

## Expected behavior
After creating more than one ar, all analysis request's should apperar in the next page for barcode printing

**Comment by xispa** [comment]
Fixed in https://github.com/senaite/senaite.core/pull/1316
