### ISSUE TITLE
Reason for rejection not available when rejecting samples

### ISSUE THREAD

**Issue by cmaphorisa** [bhp-lims/bhp.lims#230]
## Steps to reproduce
Create requisition, send to lab, receive, reject
## Current behavior
The system does not ask you for the reason for rejection
## Expected behavior
Whenever you reject the system should ask for the reason for rejection

**Comment by xispa** [comment]
Hi @cmaphorisa I've tested in pilot instance and it works as expected:

1. Go to Samples list
2. Press the filter "At reception"
3. Select any of the Samples (you can choose more than one)
4. Press the button "Reject"
5. A view like follows should appear:

![Captura de 2019-04-12 10-19-17](https://user-images.githubusercontent.com/832627/56022826-da00ff80-5d0c-11e9-9f75-33204e6a6e3d.png)

Please confirm this is happening in P-System only. The fix [SC#1309 Added Samples rejection view](https://github.com/senaite/senaite.core/pull/1309) is included in the latest release, that hasn't been yet deployed in P-System

**Comment by cmaphorisa** [comment]
It works fine in the pilot. Thanks
