### ISSUE TITLE
Some hematology results cannot be verified

### ISSUE THREAD

**Issue by cmaphorisa** [bhp-lims/bhp.lims#231]
## Steps to reproduce
Receive, sent to POT, receive at POT, enter results
## Current behavior
Some analytes appear as un-assigned instead of verified and prevent the publish process
## Screenshot (optional)
<img width="1211" alt="Screenshot 2019-04-12 at 09 50" src="https://user-images.githubusercontent.com/41732301/56021600-27c83880-5d0a-11e9-87bc-3ea17ff29e50.png">

**Comment by xispa** [comment]
`Unassigned` status refers to the fact the analysis has not been assigned to any worksheet. You are not using worksheets at the moment, so you can dismiss this status. Rather, before proceeding with the verification you need to submit first the results:

1. Select Monocytes analysis (you can select all them at once if you like)
2. At the bottom of the list, press the "Submit" button (if you've selected an analysis without a result, you'll need to set the result and press "Save" button first)
3. Analyses will transition to `To be verified` status
4. Other user with labman privileges will be able to verify those analyses thereafter

Please confirm

**Comment by cmaphorisa** [comment]
We used Chrome and it refused to save and submit. Then we used firefox and it managed to save and submit successfully. It seems it was a browser issue
