### ISSUE TITLE
Results report not showing name of person who verified by or date of verification

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#236]
## Steps to reproduce
Order an AR
Send to Lab
Receive at reception
Send to point of testing
Receive at point of testing
Process
Verify
Publish

## Current behavior

Results report not showing name of person who verified by or date of verification

## Expected behavior
Results report not show name of person who verified by AND  date of verification

**Comment by xispa** [comment]
@MoffatMore can you take care of this one?

**Comment by MoffatMore** [comment]
Yes i will take care of it Sir.

**Comment by xispa** [comment]
This issue happens from time to time, not always. Thus, this is not related to the results report template itself, rather with user logged in?

**Comment by cmaphorisa** [comment]
[09604AAB36.pdf](https://github.com/bhp-lims/bhp.lims/files/3207666/09604AAB36.pdf)
