### ISSUE TITLE
Enable critical result alert for RNA PCR result >39 copies per ml

### ISSUE THREAD

**Issue by cmaphorisa** [bhp-lims/bhp.lims#239]
## Expected behavior
For any RNA PCR result that is 40 and above the system should trigger an alert for a critical result notification to the site by email.

**Comment by xispa** [comment]
As we discussed in our last meeting, we will re-enable the panic level range. So if there is no grade defined for a given analysis (RNA PCR in this case), the panic range will be used to trigger the panic level notification message

**Comment by xispa** [comment]
@cmaphorisa , please test this one in pilot. Note that `max_panic` of 40 copies/ml has been set for analysis "HIV Viral Load (RNA PCR)" (keyword `AVL`). Thanks

**Comment by cmaphorisa** [comment]
@xispa I tested it in the pilot. It gives an error. See attached
<img width="1440" alt="Screenshot 2019-05-29 at 14 18 13" src="https://user-images.githubusercontent.com/41732301/58569328-35903980-8236-11e9-9d78-b366310f96ab.png">
<img width="1440" alt="Screenshot 2019-05-29 at 14 19 40" src="https://user-images.githubusercontent.com/41732301/58569437-67090500-8236-11e9-97f3-9b17b9d367c6.png">

**Comment by xispa** [comment]
It should work now, please try again:
http://localhost:8080/senaite/analysisrequests/publish?items=e63835488cca4a9394b2d476f93e6dc2

Just missed to update the results report template from pilot.
BTW, the panic level pop-up was displayed and worked properly?

**Comment by cmaphorisa** [comment]
Its now working as expected
