### ISSUE TITLE
The other partitions should not follow the partition that is sent to testing

### ISSUE THREAD

**Issue by cmaphorisa** [bhp-lims/bhp.lims#246]
## Current behavior
Once a partition is sent to point of testing the rest of the partitions follow it and they are prevented from being stored

## Expected behavior
The storage partitions should remain at reception and allow for storing

**Comment by xispa** [comment]
@cmaphorisa , fix deployed in pilot. Please test

![Captura de 2019-07-23 22-53-18](https://user-images.githubusercontent.com/832627/61749668-90ac5b80-ada3-11e9-9400-c5b8b9d6aa01.png)
