### ISSUE TITLE
Samples for client 124002 from 06/06/2019 refuse to transition from shipped state to at reception

### ISSUE THREAD

**Issue by cmaphorisa** [bhp-lims/bhp.lims#250]
## Screenshot (optional)
<img width="1200" alt="Screenshot 2019-06-07 at 09 58 39" src="https://user-images.githubusercontent.com/41732301/59090204-69412280-890c-11e9-98c5-b1564f9b24e4.png">

**Comment by xispa** [comment]
Resolved with remote support, using `client_reserved`. We will restart client1 and client2 today night. Please report back if same problem occurs with other Samples in future.
