### ISSUE TITLE
Sample cannot change status after being shipped to the lab

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#253]
## Steps to reproduce
1. order an analysis request
2. send to the lab

## Current behavior
the status of samples wont change when sending the sample to the lab

## Expected behavior
the sample should change the status immediately after sent to the lab

## Screenshot (optional)
<img width="1440" alt="Screenshot 2019-06-18 at 10 05 52" src="https://user-images.githubusercontent.com/12894381/59665620-8b139280-91b3-11e9-8eee-28c0c0fee4d4.png">

**Comment by MoffatMore** [comment]
And also we have another samples from HPTN084 that cant be received at reception
Find the attached snapshot of the samples below

<img width="1440" alt="Screenshot 2019-06-18 at 16 39 30" src="https://user-images.githubusercontent.com/12894381/59693760-b1532580-91e7-11e9-919a-dc06abbe2c54.png">

**Comment by xispa** [comment]
Investigating this issue in detail. I restarted the clients and it works now.
If it happens again, connect through SSH to the production server and restart the clients as follows:

```
$ sudo supervisorctl restart senaitelims_zeoclient1
$ sudo supervisorctl restart senaitelims_zeoclient2
```

@MoffatMore , ask Thuso and Coulson if they can grant you access. If so, Thuso only needs to add your RSA key in `/home/senaite/.ssh/authorized_keys` and you'll be able to login to production.
