### ISSUE TITLE
All results for RNA PCR trigger panic level alert

### ISSUE THREAD

**Issue by cmaphorisa** [bhp-lims/bhp.lims#256]
## Current behavior
All results for RNA PCR trigger panic level alert regardless of the value
## Expected behavior
Only results >39 copies/ml should trigger panic levels

**Comment by xispa** [comment]
@cmaphorisa I've tested in my development environment and is working as expected. I've also checked the specifications xls from production instance were correct and the code version as well. This only happens when you use "<40" as the result (with detection limit value).

**Comment by xispa** [comment]
@cmaphorisa this has been fixed in production. You can check with 09102AAC83 (no panic alert) and 01102AAL47 (panic alert)
