### ISSUE TITLE
Value for Gender cannot be copied across columns in Analysis Request Add form

### ISSUE THREAD

**Issue by xispa** [bhp-lims/bhp.lims#74]
## Steps to reproduce

1. Go to Analysis Request Add form
2. Set 2 in the input box located at the top of the form and click Add
3. Check the option "Male" for field "Gender", in the first column
4. Click to the icon to copy field across columns
5. Option "Male" does not get selected in second column

## Current behavior

Sex value cannot be copied across columns when the copy icon is used

## Expected behavior

Sex value can be copied across columns when the copy icon is used

**Comment by cmaphorisa** [comment]
I tested and it's not working

**Comment by xispa** [comment]
https://github.com/senaite/senaite.core/pull/1310
